HybridEncoder:
  eval_spatial_size:
    - 640
    - 640
RTDETRTransformer:
  eval_spatial_size:
    - 640
    - 640

checkpoint_step: 1
clip_max_norm: -1
ema:
  decay: 0.9999
  type: ModelEMA
  warmups: 2000
epoches: 1
lr_scheduler: null
lr_warmup:
  end_factor: 1.0
  start_factor: 0.001
  total_iters: 25
  type: LinearLR

optimizer:
  betas:
    - 0.9
    - 0.999
  lr: 0.0002
  type: Adam
  weight_decay: 0.0001
remap_mscoco_category: false
save_ema: false
save_optimizer: false
