__include__:
- rtdetr_r18vd_6x_coco.yml
amsgrad: false
beta1: 0.9
beta2: 0.999
checkpoints_interval: 1
clip_gradient_norm: false
clip_gradient_norm_value: 0.1
enable_warmup: true
input_size: 1000
learning_rate: 0.0001
num_classes: 3
num_epochs: 20
optimizer: Adam
remap_mscoco_category: false
save_best_checkpoint: false
save_last_checkpoint: false
scheduler: Without scheduler
sly_metadata:
  classes:
  - test2
  - "Motorpendelst\xFCtze"
  - cucumber
  model: rtdetr_r18vd_coco
  project_id: 36697
  project_name: cucumber-training
train_batch_size: 2
train_dataloader:
  dataset:
    ann_file: None/coco_anno.json
    img_folder: None/img
val_batch_size: 2
val_dataloader:
  dataset:
    ann_file: None/coco_anno.json
    img_folder: None/img
validation_interval: 1
warmup_iterations: 2
weight_decay: 0.0001
