__include__:
- rtdetr_r18vd_6x_coco.yml
num_classes: 3
remap_mscoco_category: false
sly_metadata:
  classes:
  - test2
  - "Motorpendelst\xFCtze"
  - cucumber
  model: rtdetr_r18vd_coco
  project_id: 36697
  project_name: cucumber-training
train_dataloader:
  dataset:
    ann_file: /Users/iwatkot/Documents/Supervisely/RT-DETR/supervisely_integration/train/temp/converted/cucumber-training/train/coco_anno.json
    img_folder: /Users/iwatkot/Documents/Supervisely/RT-DETR/supervisely_integration/train/temp/converted/cucumber-training/train/img
val_dataloader:
  dataset:
    ann_file: /Users/iwatkot/Documents/Supervisely/RT-DETR/supervisely_integration/train/temp/converted/cucumber-training/val/coco_anno.json
    img_folder: /Users/iwatkot/Documents/Supervisely/RT-DETR/supervisely_integration/train/temp/converted/cucumber-training/val/img
